import React, { createContext, useContext, useState, useCallback } from "react";

type Language = "en" | "hr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.hosting": "Hosting",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.support": "Support",
    "nav.getStarted": "Get started",

    // Hero
    "hero.badge": "EU-Based Hosting · Global Coverage",
    "hero.title": "Fast, affordable hosting — worldwide",
    "hero.subtitle": "Up to 50% cheaper than Bluehost. Your data stays in the EU. Faster load times for your local customers.",
    "hero.cta": "Start for €1.49/mo",
    "hero.ctaSecondary": "See all plans",

    // Hero stats
    "hero.stat1.value": "€1.49",
    "hero.stat1.label": "Starting price/mo",
    "hero.stat2.value": "99.9%",
    "hero.stat2.label": "Uptime SLA",
    "hero.stat3.value": "50%",
    "hero.stat3.label": "Cheaper than Bluehost",
    "hero.stat4.value": "<20ms",
    "hero.stat4.label": "Low Latency Worldwide",

    // Trust bar
    "trust.ssl": "Free SSL on all plans",
    "trust.monitoring": "24/7 monitoring",
    "trust.gdpr": "GDPR compliant · EU data",
    "trust.cpanel": "cPanel included free",
    "trust.backups": "Daily backups",

    // Features
    "features.title": "Everything you need to host with confidence",
    "features.subtitle": "Built for small businesses, agencies, and developers across the region",
    "features.datacenter.title": "EU Data Centers",
    "features.datacenter.desc": "Your data stays in the EU. Choose your server location at signup for optimal performance.",
    "features.uptime.title": "99.9% uptime SLA",
    "features.uptime.desc": "Redundant power, UPS backup, and 24/7 monitoring keep your sites online.",
    "features.ssl.title": "Free SSL + GDPR",
    "features.ssl.desc": "Every plan includes SSL certificates and full GDPR compliance for EU businesses.",
    "features.cpanel.title": "cPanel control panel",
    "features.cpanel.desc": "Industry-standard cPanel on every plan. Manage files, databases, and email easily.",
    "features.ssd.title": "SSD storage",
    "features.ssd.desc": "All plans run on fast SSD drives. No spinning disks — significantly faster page loads.",
    "features.wordpress.title": "1-click WordPress",
    "features.wordpress.desc": "Install WordPress, Joomla, or Drupal in one click via the Softaculous installer.",

    // Pricing
    "pricing.title": "Simple, transparent pricing",
    "pricing.subtitle": "No hidden fees. No surprise renewals. What you see is what you pay.",
    "pricing.monthly": "Monthly",
    "pricing.12months": "12 Months",
    "pricing.24months": "24 Months",
    "pricing.36months": "36 Months",
    "pricing.save15": "Save 15%",
    "pricing.save25": "Save 25%",
    "pricing.basic": "Basic",
    "pricing.basic.desc": "Perfect for small sites and personal projects.",
    "pricing.standard": "Standard",
    "pricing.standard.desc": "The most popular choice for growing websites.",
    "pricing.business": "Business",
    "pricing.business.desc": "For growing companies that need more power.",
    "pricing.agency": "Agency",
    "pricing.agency.desc": "For resellers and agencies managing multiple sites.",
    "pricing.mo": "/mo",
    "pricing.mostPopular": "Most popular",
    "pricing.getStarted": "Get started",
    "pricing.unlimited": "Unlimited",
    "pricing.feature.websites": "Websites",
    "pricing.feature.storage": "SSD Storage",
    "pricing.feature.visits": "Visits/mo",
    "pricing.feature.ssl": "Free SSL",
    "pricing.feature.cpanel": "cPanel",
    "pricing.feature.backup": "Daily backup",
    "pricing.feature.support": "Support",
    "pricing.feature.cpu": "CPU",
    "pricing.support.standard": "Email support",
    "pricing.support.priority": "Priority support",
    "pricing.support.phone": "Phone + chat support",
    "pricing.support.dedicated": "Dedicated support line",

    // Why choose us
    "why.title": "Why businesses choose WebWeaver",
    "why.subtitle": "Local hosting with a real advantage",
    "why.1.title": "Servers close to your audience",
    "why.1.desc": "Choose from multiple data center locations worldwide. Your website loads faster when the data doesn't travel halfway around the globe.",
    "why.2.title": "Half the price of global providers",
    "why.2.desc": "We pass our low infrastructure costs directly to you. No VC investors to satisfy — just fair pricing.",
    "why.3.title": "Multilingual support team",
    "why.3.desc": "Our support team speaks multiple languages and understands diverse business needs across the globe.",
    "why.4.title": "GDPR by default",
    "why.4.desc": "All data stored in the EU. No cross-Atlantic transfers. No compliance headaches for your clients or customers.",

    // Server locations
    "onboarding.serverLocation": "Server location",
    "onboarding.serverLocation.desc": "Choose where your server will be hosted for optimal performance.",
    "onboarding.serverLocation.frankfurt": "Frankfurt, Germany (EU)",
    "onboarding.serverLocation.amsterdam": "Amsterdam, Netherlands (EU)",
    "onboarding.serverLocation.helsinki": "Helsinki, Finland (EU)",
    "onboarding.serverLocation.newyork": "New York, USA",
    "onboarding.serverLocation.singapore": "Singapore (APAC)",

    // CTA band
    "cta.title": "Ready to switch to faster, cheaper hosting?",
    "cta.subtitle": "Start today. Free migration from your current host included on Business and Agency plans.",
    "cta.button": "Start for €1.49/mo",

    // About
    "about.title": "About Us",
    "about.subtitle": "We're a team of developers and hosting enthusiasts on a mission to make the web faster and more accessible.",
    "about.story.title": "Our Story",
    "about.story.text": "Founded in 2020, we started with a simple idea: hosting should be fast, affordable, and stress-free. What began as a small project serving local businesses has grown into a platform trusted by thousands across Europe.",
    "about.mission.title": "Our Mission",
    "about.mission.text": "To empower individuals and businesses to build their online presence without the technical headaches. We handle the infrastructure so you can focus on what matters.",
    "about.values.title": "Our Values",
    "about.values.speed": "Speed First",
    "about.values.speedDesc": "Every millisecond counts. We optimize relentlessly.",
    "about.values.trust": "Trust & Transparency",
    "about.values.trustDesc": "No hidden fees. No surprises. Ever.",
    "about.values.support": "Human Support",
    "about.values.supportDesc": "Real people, real help, real fast.",

    // Contact
    "contact.title": "Get in Touch",
    "contact.subtitle": "Have a question or need help? We'd love to hear from you.",
    "contact.name": "Your Name",
    "contact.email": "Email Address",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.success": "Message sent! We'll get back to you within 24 hours.",
    "contact.info.title": "Contact Information",
    "contact.info.email": "support@webweaver.hr",
    "contact.info.phone": "+385 1 234 5678",
    "contact.info.address": "European Union",

    // FAQ
    "faq.title": "Knowledge Base",
    "faq.subtitle": "Find answers to common questions about our services.",
    "faq.search": "Search articles...",
    "faq.cat.hosting": "Hosting",
    "faq.cat.domains": "Domains",
    "faq.cat.billing": "Billing",
    "faq.cat.security": "Security",
    "faq.cat.all": "All",
    "faq.q1": "How do I migrate my existing website?",
    "faq.a1": "We offer free migration for all plans. Simply contact our support team and we'll handle the entire process, usually within 24 hours with zero downtime.",
    "faq.q2": "What uptime guarantee do you provide?",
    "faq.a2": "We guarantee 99.9% uptime across all plans. If we fail to meet this, you'll receive credit on your account proportional to the downtime.",
    "faq.q3": "Can I register a .hr domain?",
    "faq.a3": "Yes! We support .hr domains along with hundreds of other extensions including .com, .eu, .net, .org, and many more.",
    "faq.q4": "How does domain transfer work?",
    "faq.a4": "Unlock your domain at your current registrar, obtain the EPP/auth code, and initiate the transfer through our dashboard. Most transfers complete within 5-7 days.",
    "faq.q5": "What payment methods do you accept?",
    "faq.a5": "We accept all major credit cards (Visa, Mastercard, American Express), PayPal, and bank transfers for annual plans.",
    "faq.q6": "Can I upgrade my plan at any time?",
    "faq.a6": "Absolutely. You can upgrade or downgrade at any time. When upgrading, you'll only pay the prorated difference for the remaining billing period.",
    "faq.q7": "Is SSL included free with hosting?",
    "faq.a7": "Yes, all hosting plans include free Let's Encrypt SSL certificates that auto-renew. Premium Wildcard and EV certificates are also available.",
    "faq.q8": "Do you provide DDoS protection?",
    "faq.a8": "All plans include basic DDoS mitigation. Business and Enterprise plans feature advanced protection with real-time threat monitoring.",

    // Auth
    "auth.login": "Log In",
    "auth.register": "Create Account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.name": "Full Name",
    "auth.forgotPassword": "Forgot password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.orContinue": "Or continue with",
    "auth.google": "Google",
    "auth.github": "GitHub",
    "auth.error": "Error",
    "auth.loginSuccess": "Welcome back!",
    "auth.registerSuccess": "Account created!",
    "auth.checkEmail": "Check your email to confirm your account.",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters",
    "auth.logout": "Log out",

    // Onboarding
    "onboarding.step1": "Choose your plan",
    "onboarding.step2": "Set up your domain",
    "onboarding.step3": "Add extras",
    "onboarding.step4": "Review & confirm",
    "onboarding.step1.desc": "Select the plan that fits your needs.",
    "onboarding.step2.desc": "Connect your existing domain or register a new one.",
    "onboarding.step3.desc": "Enhance your hosting with optional add-ons.",
    "onboarding.step4.desc": "Review your selections before confirming.",
    "onboarding.selected": "Selected",
    "onboarding.next": "Continue",
    "onboarding.back": "Back",
    "onboarding.confirm": "Confirm & activate",
    "onboarding.existingDomain": "I have a domain",
    "onboarding.existingDomain.desc": "Connect a domain you already own.",
    "onboarding.newDomain": "Register a new domain",
    "onboarding.newDomain.desc": "Search and register a new domain name.",
    "onboarding.enterDomain": "Enter your domain name",
    "onboarding.searchDomain": "Search for a domain",
    "onboarding.domainHint": "You can always change this later in your dashboard.",
    "onboarding.plan": "Plan",
    "onboarding.domain": "Domain",
    "onboarding.extras": "Add-ons",
    "onboarding.total": "Total",
    "onboarding.extra.backup": "Automatic backups",
    "onboarding.extra.backup.desc": "Daily automated backups with one-click restore.",
    "onboarding.extra.email": "Professional email",
    "onboarding.extra.email.desc": "Custom email addresses with your domain.",
    "onboarding.extra.priority": "Priority support",
    "onboarding.extra.priority.desc": "Skip the queue with dedicated support agents.",
    "onboarding.extra.ddos": "DDoS protection",
    "onboarding.extra.ddos.desc": "Advanced protection against DDoS attacks.",
    "onboarding.chooseFreeDomain": "Choose your free domain",
    "onboarding.searchDomain.btn": "Search",
    "onboarding.domain.available": "Domain is available!",
    "onboarding.domain.taken": "This domain already exists. Please try another.",
    "onboarding.domain.checking": "Checking availability...",
    "onboarding.domain.invalid": "Please enter a valid domain (e.g. example.com)",

    // Footer
    "footer.description": "Fast, reliable, and affordable web hosting for everyone.",
    "footer.copyright": "© 2026 WebWeaver",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.support": "Support",

    // Terms
    "terms.overline": "Agreements & Policies",
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated: March 30, 2026",
    "terms.sidebar.title": "Quick links",
    "terms.sidebar.userAgreement": "User Agreement",
    "terms.sidebar.acceptableUse": "Acceptable Use",
    "terms.sidebar.privacyNotice": "Privacy Notice",
    "terms.sidebar.domainRegistration": "Domain Registration",
    "terms.sidebar.antiSpam": "Anti-SPAM Policy",
    "terms.sidebar.refundPolicy": "Refund Policy",
    "terms.sidebar.privacyLink": "View Privacy Policy →",
    "terms.section.userAgreement.title": "User Agreement",
    "terms.section.userAgreement.p1": "By accessing or using the WebWeaver hosting platform, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this service.",
    "terms.section.userAgreement.p2": "WebWeaver reserves the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms. We will notify you of significant changes via email or through a notice on our website.",
    "terms.section.acceptableUse.title": "Acceptable Use Policy",
    "terms.section.acceptableUse.p1": "You agree to use WebWeaver services only for lawful purposes and in accordance with these Terms. You agree not to use the service:",
    "terms.section.acceptableUse.li1": "In any way that violates any applicable national or international law or regulation.",
    "terms.section.acceptableUse.li2": "To transmit any unsolicited advertising, promotional materials, or spam.",
    "terms.section.acceptableUse.li3": "To impersonate or attempt to impersonate WebWeaver, an employee, another user, or any other person or entity.",
    "terms.section.acceptableUse.li4": "To engage in any conduct that restricts or inhibits anyone's use or enjoyment of the service.",
    "terms.section.privacyNotice.title": "Privacy Notice",
    "terms.section.privacyNotice.p1": "Your privacy is important to us. Our Privacy Policy, available at webweaver.hr/privacy, explains how we collect, use, and protect your personal information. By using our service, you consent to the data practices described in that policy. All data is stored within the EU in compliance with GDPR regulations.",
    "terms.section.domainRegistration.title": "Domain Registration Agreement",
    "terms.section.domainRegistration.p1": "Domain name registrations are subject to ICANN policies and the applicable registry agreement. WebWeaver acts as a registrar and is not responsible for domain disputes, expiration, or loss of domain ownership due to failure to renew.",
    "terms.section.domainRegistration.p2": "You are responsible for providing accurate WHOIS information and keeping it up to date. Providing false WHOIS data may result in domain cancellation in accordance with ICANN policy.",
    "terms.section.antiSpam.title": "Anti-SPAM Policy",
    "terms.section.antiSpam.p1": "WebWeaver maintains a strict zero-tolerance policy regarding unsolicited commercial email (spam). Accounts found sending bulk unsolicited emails will be immediately suspended without refund. We actively monitor for abuse and cooperate with anti-spam organizations.",
    "terms.section.refundPolicy.title": "Refund Policy",
    "terms.section.refundPolicy.p1": "WebWeaver offers a 30-day money-back guarantee on all new hosting plans. If you are not satisfied with our service, you may request a full refund within 30 days of your initial purchase.",
    "terms.section.refundPolicy.p2": "Domain registration fees, SSL certificates, and other add-on services are non-refundable. Refund requests after the 30-day period will be evaluated on a case-by-case basis.",
    "terms.section.payment.title": "Payment & Auto-Renewal",
    "terms.section.payment.p1": "All hosting plans are billed in advance according to the billing cycle you select (monthly, 12-month, 24-month, or 36-month). Prices are listed in EUR and include applicable taxes for EU customers.",
    "terms.section.payment.p2": "Your subscription will automatically renew at the end of each billing cycle at the then-current renewal rate unless cancelled. You may cancel auto-renewal at any time through your account dashboard or by contacting support.",
    "terms.section.termination.title": "Termination",
    "terms.section.termination.p1": "WebWeaver may terminate or suspend your account immediately, without prior notice or liability, for any reason, including breach of these Terms. Upon termination, your right to use the service will immediately cease. You may request a copy of your data within 30 days of termination.",
    "terms.section.liability.title": "Limitation of Liability",
    "terms.section.liability.p1": "In no event shall WebWeaver, its directors, employees, partners, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the service. Our total liability shall not exceed the amount you paid for the service in the preceding 12 months.",
    "terms.section.gdpr.title": "GDPR Compliance",
    "terms.section.gdpr.p1": "WebWeaver is fully compliant with the General Data Protection Regulation (GDPR). All customer data is stored within EU data centers. You have the right to access, rectify, erase, restrict processing, and port your personal data. To exercise these rights, contact our Data Protection Officer at dpo@webweaver.hr.",
    "terms.section.governing.title": "Governing Law",
    "terms.section.governing.p1": "These Terms shall be governed by and construed in accordance with the laws of the European Union and the Republic of Croatia, without regard to conflict of law provisions. Any disputes arising from these terms will be resolved in the competent courts of Zagreb, Croatia.",

    // Privacy
    "privacy.overline": "Privacy Center",
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "We are committed to protecting your data. Here's how we handle your information at WebWeaver.",
    "privacy.accordion.whereData.q": "Where does my data go?",
    "privacy.accordion.whereData.a": "All your data is stored exclusively in EU data centers (Frankfurt, Amsterdam, or Helsinki — depending on your chosen server location). We never transfer personal data outside the European Economic Area without your explicit consent and adequate safeguards.",
    "privacy.accordion.whatCollect.q": "What information do we collect?",
    "privacy.accordion.whatCollect.a": "We collect information you provide directly (name, email, payment details), technical data (IP address, browser type, device info), and usage data (pages visited, features used). We only collect what is necessary to provide and improve our services.",
    "privacy.accordion.howUsed.q": "How is my data used?",
    "privacy.accordion.howUsed.a": "Your data is used to provide hosting services, process payments, send service communications, provide customer support, and improve our platform. We never sell your personal data to third parties. Data is shared only with essential service providers (payment processors, infrastructure partners) under strict contractual obligations.",
    "privacy.card.dataRequests.title": "Data Requests",
    "privacy.card.dataRequests.desc": "Request a copy of all personal data we hold about you. We respond to all GDPR data access requests within 30 days.",
    "privacy.card.cookies.title": "Cookie Notice",
    "privacy.card.cookies.desc": "We use essential cookies for site functionality and optional analytics cookies. You can manage your preferences at any time.",
    "privacy.card.security.title": "Security Practices",
    "privacy.card.security.desc": "Your data is protected with AES-256 encryption at rest, TLS 1.3 in transit, and regular third-party security audits.",
    "privacy.card.gdprRights.title": "Your GDPR Rights",
    "privacy.card.gdprRights.desc": "Access, rectify, erase, restrict, or port your data. Object to processing at any time by contacting our DPO.",
    "privacy.full.title": "Full Privacy Notice",
    "privacy.full.collection.title": "Information We Collect",
    "privacy.full.collection.p1": "We collect personal information you provide when creating an account (name, email, billing address), payment information processed securely through our payment provider, technical information automatically collected (IP addresses, browser type, operating system, referral URLs), and usage information about how you interact with our services.",
    "privacy.full.sharing.title": "Data Sharing",
    "privacy.full.sharing.p1": "We share data only with: payment processors (Stripe) to complete transactions, infrastructure providers (EU-based data centers) for hosting, domain registries (ICANN-accredited) for domain services, and law enforcement when legally required. All third-party providers are contractually bound to GDPR-compliant data processing agreements.",
    "privacy.full.cookies.title": "Cookies & Tracking",
    "privacy.full.cookies.p1": "We use strictly necessary cookies for authentication and session management, and optional analytics cookies (with your consent) to improve our services. You can disable non-essential cookies via the cookie banner or your browser settings. We do not use cross-site tracking or sell data to advertisers.",
    "privacy.full.security.title": "Security Measures",
    "privacy.full.security.p1": "We protect your data with AES-256 encryption at rest, TLS 1.3 encryption in transit, regular penetration testing and vulnerability assessments, role-based access controls, 24/7 infrastructure monitoring, and automated threat detection. We maintain SOC 2-aligned security practices.",
    "privacy.full.rights.title": "Your Rights (GDPR)",
    "privacy.full.rights.p1": "Under the GDPR, you have the right to: access your personal data, rectify inaccurate data, erase your data ('right to be forgotten'), restrict processing, data portability, object to processing, and withdraw consent. To exercise any of these rights, email dpo@webweaver.hr. We will respond within 30 days.",
    "privacy.full.retention.title": "Data Retention",
    "privacy.full.retention.p1": "We retain your personal data only as long as necessary to provide services and comply with legal obligations. Account data is kept for the duration of your account plus 90 days. Billing records are retained for 7 years as required by EU tax regulations. Server logs are automatically purged after 90 days.",
    "privacy.full.children.title": "Children's Privacy",
    "privacy.full.children.p1": "Our services are not directed to individuals under the age of 16. We do not knowingly collect personal information from children. If we become aware that we have collected data from a child under 16, we will take steps to delete that information promptly.",
    "privacy.full.contact.title": "Contact Us",
    "privacy.full.contact.p1": "For privacy-related inquiries, contact our Data Protection Officer at dpo@webweaver.hr. For general questions, reach us at support@webweaver.hr or +385 1 234 5678. Our registered address is in the European Union.",
    "privacy.full.termsLink": "For information about our service terms, see our",
  },
  hr: {
    // Nav
    "nav.hosting": "Hosting",
    "nav.pricing": "Cijene",
    "nav.about": "O nama",
    "nav.support": "Podrška",
    "nav.getStarted": "Započni",

    // Hero
    "hero.badge": "EU hosting · Globalna pokrivenost",
    "hero.title": "Brz, pristupačan hosting — diljem svijeta",
    "hero.subtitle": "Do 50% jeftinije od Bluehosta. Vaši podaci ostaju u EU. Brže učitavanje za vaše lokalne korisnike.",
    "hero.cta": "Započni za €1,49/mj",
    "hero.ctaSecondary": "Pogledaj sve planove",

    // Hero stats
    "hero.stat1.value": "€1,49",
    "hero.stat1.label": "Početna cijena/mj",
    "hero.stat2.value": "99,9%",
    "hero.stat2.label": "SLA dostupnost",
    "hero.stat3.value": "50%",
    "hero.stat3.label": "Jeftinije od Bluehosta",
    "hero.stat4.value": "<20ms",
    "hero.stat4.label": "Niska latencija globalno",

    // Trust bar
    "trust.ssl": "Besplatni SSL na svim planovima",
    "trust.monitoring": "24/7 nadzor",
    "trust.gdpr": "GDPR sukladan · EU podaci",
    "trust.cpanel": "cPanel uključen besplatno",
    "trust.backups": "Dnevne sigurnosne kopije",

    // Features
    "features.title": "Sve što trebate za hosting s povjerenjem",
    "features.subtitle": "Napravljeno za male tvrtke, agencije i programere diljem regije",
    "features.datacenter.title": "EU podatkovni centri",
    "features.datacenter.desc": "Vaši podaci ostaju u EU. Odaberite lokaciju servera pri prijavi za optimalne performanse.",
    "features.uptime.title": "99,9% SLA dostupnost",
    "features.uptime.desc": "Redundantno napajanje, UPS i 24/7 nadzor drže vaše stranice online.",
    "features.ssl.title": "Besplatni SSL + GDPR",
    "features.ssl.desc": "Svaki plan uključuje SSL certifikate i potpunu GDPR sukladnost za EU tvrtke.",
    "features.cpanel.title": "cPanel upravljačka ploča",
    "features.cpanel.desc": "Industrijski standard cPanel na svakom planu. Upravljajte datotekama, bazama i emailom.",
    "features.ssd.title": "SSD pohrana",
    "features.ssd.desc": "Svi planovi rade na brzim SSD diskovima. Bez mehaničkih diskova — značajno brže učitavanje.",
    "features.wordpress.title": "WordPress jednim klikom",
    "features.wordpress.desc": "Instalirajte WordPress, Joomla ili Drupal jednim klikom putem Softaculous instalera.",

    // Pricing
    "pricing.title": "Jednostavne, transparentne cijene",
    "pricing.subtitle": "Bez skrivenih naknada. Bez iznenađenja pri obnovi. Što vidite, to i plaćate.",
    "pricing.monthly": "Mjesečno",
    "pricing.12months": "12 Mjeseci",
    "pricing.24months": "24 Mjeseca",
    "pricing.36months": "36 Mjeseci",
    "pricing.save15": "Uštedite 15%",
    "pricing.save25": "Uštedite 25%",
    "pricing.basic": "Basic",
    "pricing.basic.desc": "Idealno za male stranice i osobne projekte.",
    "pricing.standard": "Standard",
    "pricing.standard.desc": "Najpopularniji izbor za rastuće web stranice.",
    "pricing.business": "Business",
    "pricing.business.desc": "Za rastuće tvrtke kojima treba više snage.",
    "pricing.agency": "Agency",
    "pricing.agency.desc": "Za preprodavače i agencije koje upravljaju višestrukim stranicama.",
    "pricing.mo": "/mj",
    "pricing.mostPopular": "Najpopularnije",
    "pricing.getStarted": "Započni",
    "pricing.unlimited": "Neograničeno",
    "pricing.feature.websites": "Web stranice",
    "pricing.feature.storage": "SSD Pohrana",
    "pricing.feature.visits": "Posjeta/mj",
    "pricing.feature.ssl": "Besplatni SSL",
    "pricing.feature.cpanel": "cPanel",
    "pricing.feature.backup": "Dnevna kopija",
    "pricing.feature.support": "Podrška",
    "pricing.feature.cpu": "CPU",
    "pricing.support.standard": "Email podrška",
    "pricing.support.priority": "Prioritetna podrška",
    "pricing.support.phone": "Telefon + chat podrška",
    "pricing.support.dedicated": "Dedicirani kanal podrške",

    // Why choose us
    "why.title": "Zašto tvrtke biraju WebWeaver",
    "why.subtitle": "Lokalni hosting s pravom prednošću",
    "why.1.title": "Serveri blizu vaše publike",
    "why.1.desc": "Odaberite među više lokacija podatkovnih centara diljem svijeta. Stranica se brže učitava kad podaci ne putuju oko pola svijeta.",
    "why.2.title": "Upola jeftinije od globalnih pružatelja",
    "why.2.desc": "Naše niske troškove infrastrukture prenosimo izravno na vas. Bez VC investitora — samo fer cijene.",
    "why.3.title": "Višejezični tim podrške",
    "why.3.desc": "Naš tim za podršku govori više jezika i razumije raznolike poslovne potrebe diljem svijeta.",
    "why.4.title": "GDPR po defaultu",
    "why.4.desc": "Svi podaci pohranjeni u EU. Bez transatlantskih prijenosa. Bez problema s uskladnošću za vaše klijente.",

    // Server locations
    "onboarding.serverLocation": "Lokacija servera",
    "onboarding.serverLocation.desc": "Odaberite gdje će vaš server biti smješten za optimalne performanse.",
    "onboarding.serverLocation.frankfurt": "Frankfurt, Njemačka (EU)",
    "onboarding.serverLocation.amsterdam": "Amsterdam, Nizozemska (EU)",
    "onboarding.serverLocation.helsinki": "Helsinki, Finska (EU)",
    "onboarding.serverLocation.newyork": "New York, SAD",
    "onboarding.serverLocation.singapore": "Singapur (APAC)",

    // CTA band
    "cta.title": "Spremni za prelazak na brži, jeftiniji hosting?",
    "cta.subtitle": "Započnite danas. Besplatna migracija s vašeg trenutnog hosta uključena na Business i Agency planovima.",
    "cta.button": "Započni za €1,49/mj",

    // About
    "about.title": "O nama",
    "about.subtitle": "Tim programera i hosting entuzijasta s misijom da web učinimo bržim i dostupnijim.",
    "about.story.title": "Naša priča",
    "about.story.text": "Osnovani 2020. godine, krenuli smo s jednostavnom idejom: hosting treba biti brz, pristupačan i bez stresa. Ono što je počelo kao mali projekt za lokalne tvrtke izraslo je u platformu kojoj vjeruju tisuće korisnika diljem Europe.",
    "about.mission.title": "Naša misija",
    "about.mission.text": "Osnažiti pojedince i tvrtke da izgrade svoju online prisutnost bez tehničkih glavobolja. Mi brinemo o infrastrukturi kako biste se vi mogli fokusirati na ono što je važno.",
    "about.values.title": "Naše vrijednosti",
    "about.values.speed": "Brzina na prvom mjestu",
    "about.values.speedDesc": "Svaka milisekunda je važna. Optimiziramo bez prestanka.",
    "about.values.trust": "Povjerenje i transparentnost",
    "about.values.trustDesc": "Bez skrivenih naknada. Bez iznenađenja. Nikada.",
    "about.values.support": "Ljudska podrška",
    "about.values.supportDesc": "Stvarni ljudi, stvarna pomoć, stvarno brzo.",

    // Contact
    "contact.title": "Kontaktirajte nas",
    "contact.subtitle": "Imate pitanje ili trebate pomoć? Rado ćemo vas čuti.",
    "contact.name": "Vaše ime",
    "contact.email": "Email adresa",
    "contact.subject": "Predmet",
    "contact.message": "Poruka",
    "contact.send": "Pošalji poruku",
    "contact.success": "Poruka poslana! Odgovorit ćemo vam u roku od 24 sata.",
    "contact.info.title": "Kontakt informacije",
    "contact.info.email": "podrska@webweaver.hr",
    "contact.info.phone": "+385 1 234 5678",
    "contact.info.address": "Europska unija",

    // FAQ
    "faq.title": "Baza znanja",
    "faq.subtitle": "Pronađite odgovore na česta pitanja o našim uslugama.",
    "faq.search": "Pretraži članke...",
    "faq.cat.hosting": "Hosting",
    "faq.cat.domains": "Domene",
    "faq.cat.billing": "Naplata",
    "faq.cat.security": "Sigurnost",
    "faq.cat.all": "Sve",
    "faq.q1": "Kako mogu migrirati postojeću web stranicu?",
    "faq.a1": "Nudimo besplatnu migraciju za sve planove. Kontaktirajte naš tim za podršku i mi ćemo obaviti cijeli proces, obično unutar 24 sata bez prekida rada.",
    "faq.q2": "Kakvu garanciju dostupnosti pružate?",
    "faq.a2": "Garantiramo 99.9% dostupnost za sve planove. Ako ne ispunimo ovaj standard, dobit ćete kredit na račun razmjeran vremenu nedostupnosti.",
    "faq.q3": "Mogu li registrirati .hr domenu?",
    "faq.a3": "Da! Podržavamo .hr domene zajedno sa stotinama drugih ekstenzija uključujući .com, .eu, .net, .org i mnoge druge.",
    "faq.q4": "Kako funkcionira transfer domene?",
    "faq.a4": "Otključajte domenu kod trenutnog registra, pribavite EPP/auth kod i pokrenite transfer putem naše upravljačke ploče. Većina transfera se završi u 5-7 dana.",
    "faq.q5": "Koje načine plaćanja prihvaćate?",
    "faq.a5": "Prihvaćamo sve veće kreditne kartice (Visa, Mastercard, American Express), PayPal i bankovne transfere za godišnje planove.",
    "faq.q6": "Mogu li nadograditi plan u bilo kojem trenutku?",
    "faq.a6": "Apsolutno. Možete nadograditi ili sniziti plan u bilo kojem trenutku. Kod nadogradnje plaćate samo proporcionalni iznos za preostalo obračunsko razdoblje.",
    "faq.q7": "Je li SSL uključen besplatno s hostingom?",
    "faq.a7": "Da, svi hosting planovi uključuju besplatne Let's Encrypt SSL certifikate koji se automatski obnavljaju. Premium Wildcard i EV certifikati su također dostupni.",
    "faq.q8": "Pružate li DDoS zaštitu?",
    "faq.a8": "Svi planovi uključuju osnovnu DDoS zaštitu. Business i Enterprise planovi imaju naprednu zaštitu s praćenjem prijetnji u stvarnom vremenu.",

    // Auth
    "auth.login": "Prijava",
    "auth.register": "Kreiraj račun",
    "auth.email": "Email",
    "auth.password": "Lozinka",
    "auth.confirmPassword": "Potvrdi lozinku",
    "auth.name": "Puno ime",
    "auth.forgotPassword": "Zaboravili ste lozinku?",
    "auth.noAccount": "Nemate račun?",
    "auth.hasAccount": "Već imate račun?",
    "auth.orContinue": "Ili nastavite s",
    "auth.google": "Google",
    "auth.github": "GitHub",
    "auth.error": "Greška",
    "auth.loginSuccess": "Dobrodošli natrag!",
    "auth.registerSuccess": "Račun kreiran!",
    "auth.checkEmail": "Provjerite email za potvrdu računa.",
    "auth.passwordMismatch": "Lozinke se ne podudaraju",
    "auth.passwordTooShort": "Lozinka mora imati najmanje 6 znakova",
    "auth.logout": "Odjava",

    // Onboarding
    "onboarding.step1": "Odaberite plan",
    "onboarding.step2": "Postavite domenu",
    "onboarding.step3": "Dodajte dodatke",
    "onboarding.step4": "Pregled i potvrda",
    "onboarding.step1.desc": "Odaberite plan koji odgovara vašim potrebama.",
    "onboarding.step2.desc": "Povežite postojeću domenu ili registrirajte novu.",
    "onboarding.step3.desc": "Poboljšajte hosting s opcionalnim dodacima.",
    "onboarding.step4.desc": "Pregledajte odabire prije potvrde.",
    "onboarding.selected": "Odabrano",
    "onboarding.next": "Nastavi",
    "onboarding.back": "Natrag",
    "onboarding.confirm": "Potvrdi i aktiviraj",
    "onboarding.existingDomain": "Imam domenu",
    "onboarding.existingDomain.desc": "Povežite domenu koju već posjedujete.",
    "onboarding.newDomain": "Registriraj novu domenu",
    "onboarding.newDomain.desc": "Pretražite i registrirajte novi naziv domene.",
    "onboarding.enterDomain": "Unesite naziv domene",
    "onboarding.searchDomain": "Pretražite domenu",
    "onboarding.domainHint": "Uvijek možete ovo promijeniti u svom nadzornom panelu.",
    "onboarding.plan": "Plan",
    "onboarding.domain": "Domena",
    "onboarding.extras": "Dodaci",
    "onboarding.total": "Ukupno",
    "onboarding.extra.backup": "Automatske sigurnosne kopije",
    "onboarding.extra.backup.desc": "Dnevne automatske kopije s vraćanjem jednim klikom.",
    "onboarding.extra.email": "Profesionalni email",
    "onboarding.extra.email.desc": "Prilagođene email adrese s vašom domenom.",
    "onboarding.extra.priority": "Prioritetna podrška",
    "onboarding.extra.priority.desc": "Preskočite red s posvećenim agentima.",
    "onboarding.extra.ddos": "DDoS zaštita",
    "onboarding.extra.ddos.desc": "Napredna zaštita od DDoS napada.",
    "onboarding.chooseFreeDomain": "Odaberite svoju besplatnu domenu",
    "onboarding.searchDomain.btn": "Pretraži",
    "onboarding.domain.available": "Domena je dostupna!",
    "onboarding.domain.taken": "Ova domena već postoji. Pokušajte drugu.",
    "onboarding.domain.checking": "Provjera dostupnosti...",
    "onboarding.domain.invalid": "Unesite valjanu domenu (npr. primjer.com)",

    // Footer
    "footer.description": "Brz, pouzdan i pristupačan web hosting za sve.",
    "footer.copyright": "© 2026 WebWeaver",
    "footer.privacy": "Privatnost",
    "footer.terms": "Uvjeti",
    "footer.support": "Podrška",

    // Terms
    "terms.overline": "Ugovori i pravila",
    "terms.title": "Uvjeti korištenja",
    "terms.lastUpdated": "Zadnje ažuriranje: 30. ožujka 2026.",
    "terms.sidebar.title": "Brzi linkovi",
    "terms.sidebar.userAgreement": "Korisnički ugovor",
    "terms.sidebar.acceptableUse": "Prihvatljiva upotreba",
    "terms.sidebar.privacyNotice": "Obavijest o privatnosti",
    "terms.sidebar.domainRegistration": "Registracija domene",
    "terms.sidebar.antiSpam": "Anti-SPAM pravila",
    "terms.sidebar.refundPolicy": "Pravila povrata",
    "terms.sidebar.privacyLink": "Pogledaj pravila privatnosti →",
    "terms.section.userAgreement.title": "Korisnički ugovor",
    "terms.section.userAgreement.p1": "Pristupanjem ili korištenjem WebWeaver hosting platforme pristajete na ove Uvjete korištenja i sve primjenjive zakone i propise. Ako se ne slažete s bilo kojim od ovih uvjeta, zabranjeno vam je korištenje usluge.",
    "terms.section.userAgreement.p2": "WebWeaver zadržava pravo izmjene ovih uvjeta u bilo kojem trenutku. Nastavak korištenja usluge nakon izmjena znači prihvaćanje novih uvjeta. O značajnim promjenama obavijestit ćemo vas putem emaila ili obavijesti na web stranici.",
    "terms.section.acceptableUse.title": "Pravila prihvatljive upotrebe",
    "terms.section.acceptableUse.p1": "Pristajete koristiti WebWeaver usluge samo u zakonite svrhe i u skladu s ovim Uvjetima. Ne smijete koristiti uslugu:",
    "terms.section.acceptableUse.li1": "Na način koji krši bilo koji primjenjivi nacionalni ili međunarodni zakon ili propis.",
    "terms.section.acceptableUse.li2": "Za slanje neželjenih reklamnih materijala, promotivnih materijala ili spama.",
    "terms.section.acceptableUse.li3": "Za lažno predstavljanje WebWeavera, zaposlenika, drugog korisnika ili bilo koje druge osobe ili subjekta.",
    "terms.section.acceptableUse.li4": "Za sudjelovanje u ponašanju koje ograničava ili sprječava nečije korištenje usluge.",
    "terms.section.privacyNotice.title": "Obavijest o privatnosti",
    "terms.section.privacyNotice.p1": "Vaša privatnost nam je važna. Naša Pravila privatnosti, dostupna na webweaver.hr/privacy, objašnjavaju kako prikupljamo, koristimo i štitimo vaše osobne podatke. Korištenjem naše usluge pristajete na prakse opisane u tim pravilima. Svi podaci pohranjeni su u EU u skladu s GDPR-om.",
    "terms.section.domainRegistration.title": "Ugovor o registraciji domene",
    "terms.section.domainRegistration.p1": "Registracije domena podliježu ICANN pravilima i primjenjivom ugovoru registra. WebWeaver djeluje kao registar i nije odgovoran za sporove oko domene, istek ili gubitak vlasništva nad domenom.",
    "terms.section.domainRegistration.p2": "Odgovorni ste za pružanje točnih WHOIS informacija i njihovo ažuriranje. Pružanje lažnih WHOIS podataka može rezultirati otkazivanjem domene u skladu s ICANN pravilima.",
    "terms.section.antiSpam.title": "Anti-SPAM pravila",
    "terms.section.antiSpam.p1": "WebWeaver održava strogu politiku nulte tolerancije prema neželjenom komercijalnom emailu (spamu). Računi za koje se utvrdi da šalju masovne neželjene emailove bit će odmah suspendirani bez povrata sredstava.",
    "terms.section.refundPolicy.title": "Pravila povrata",
    "terms.section.refundPolicy.p1": "WebWeaver nudi 30-dnevnu garanciju povrata novca na sve nove hosting planove. Ako niste zadovoljni uslugom, možete zatražiti puni povrat unutar 30 dana od početne kupnje.",
    "terms.section.refundPolicy.p2": "Naknade za registraciju domene, SSL certifikate i ostale dodatne usluge nisu povratne. Zahtjevi za povrat nakon 30 dana procjenjuju se od slučaja do slučaja.",
    "terms.section.payment.title": "Plaćanje i automatska obnova",
    "terms.section.payment.p1": "Svi hosting planovi naplaćuju se unaprijed prema odabranom ciklusu naplate. Cijene su navedene u EUR i uključuju primjenjive poreze za EU korisnike.",
    "terms.section.payment.p2": "Vaša pretplata automatski se obnavlja na kraju svakog ciklusa naplate po tada važećoj stopi obnove, osim ako je ne otkažete. Možete otkazati automatsku obnovu u bilo kojem trenutku putem nadzorne ploče ili kontaktiranjem podrške.",
    "terms.section.termination.title": "Raskid",
    "terms.section.termination.p1": "WebWeaver može raskinuti ili suspendirati vaš račun odmah, bez prethodne obavijesti ili odgovornosti, iz bilo kojeg razloga, uključujući kršenje ovih Uvjeta. Nakon raskida, vaše pravo korištenja usluge odmah prestaje.",
    "terms.section.liability.title": "Ograničenje odgovornosti",
    "terms.section.liability.p1": "Ni u kojem slučaju WebWeaver, njegovi direktori, zaposlenici, partneri ili podružnice neće biti odgovorni za bilo kakvu neizravnu, slučajnu, posebnu, posljedičnu ili kaznenu štetu. Naša ukupna odgovornost neće premašiti iznos koji ste platili za uslugu u prethodnih 12 mjeseci.",
    "terms.section.gdpr.title": "GDPR sukladnost",
    "terms.section.gdpr.p1": "WebWeaver je u potpunosti sukladan s Općom uredbom o zaštiti podataka (GDPR). Svi korisnički podaci pohranjeni su u EU podatkovnim centrima. Imate pravo pristupa, ispravka, brisanja, ograničenja obrade i prijenosa vaših osobnih podataka. Kontaktirajte dpo@webweaver.hr.",
    "terms.section.governing.title": "Mjerodavno pravo",
    "terms.section.governing.p1": "Ovi Uvjeti tumače se u skladu sa zakonima Europske unije i Republike Hrvatske. Svi sporovi rješavaju se pred nadležnim sudovima u Zagrebu, Hrvatska.",

    // Privacy
    "privacy.overline": "Centar privatnosti",
    "privacy.title": "Pravila privatnosti",
    "privacy.subtitle": "Posvećeni smo zaštiti vaših podataka. Evo kako postupamo s vašim informacijama u WebWeaveru.",
    "privacy.accordion.whereData.q": "Kamo idu moji podaci?",
    "privacy.accordion.whereData.a": "Svi vaši podaci pohranjeni su isključivo u EU podatkovnim centrima (Frankfurt, Amsterdam ili Helsinki). Nikada ne prenosimo osobne podatke izvan Europskog gospodarskog prostora bez vašeg izričitog pristanka.",
    "privacy.accordion.whatCollect.q": "Koje informacije prikupljamo?",
    "privacy.accordion.whatCollect.a": "Prikupljamo informacije koje nam izravno date (ime, email, podatke za plaćanje), tehničke podatke (IP adresa, tip preglednika, informacije o uređaju) i podatke o korištenju (posjećene stranice, korištene značajke). Prikupljamo samo ono što je potrebno.",
    "privacy.accordion.howUsed.q": "Kako se koriste moji podaci?",
    "privacy.accordion.howUsed.a": "Vaši podaci koriste se za pružanje hosting usluga, obradu plaćanja, slanje servisnih komunikacija, pružanje korisničke podrške i poboljšanje platforme. Nikada ne prodajemo vaše osobne podatke trećim stranama.",
    "privacy.card.dataRequests.title": "Zahtjevi za podatke",
    "privacy.card.dataRequests.desc": "Zatražite kopiju svih osobnih podataka koje imamo o vama. Na sve GDPR zahtjeve odgovaramo unutar 30 dana.",
    "privacy.card.cookies.title": "Obavijest o kolačićima",
    "privacy.card.cookies.desc": "Koristimo nužne kolačiće za funkcionalnost stranice i opcionalne analitičke kolačiće. Upravljajte postavkama u bilo kojem trenutku.",
    "privacy.card.security.title": "Sigurnosne prakse",
    "privacy.card.security.desc": "Vaši podaci zaštićeni su AES-256 enkripcijom, TLS 1.3 prijenosom i redovitim sigurnosnim revizijama treće strane.",
    "privacy.card.gdprRights.title": "Vaša GDPR prava",
    "privacy.card.gdprRights.desc": "Pristupite, ispravite, izbrišite, ograničite ili prenesite svoje podatke. Prigovorite obradi kontaktiranjem našeg DPO-a.",
    "privacy.full.title": "Potpuna obavijest o privatnosti",
    "privacy.full.collection.title": "Informacije koje prikupljamo",
    "privacy.full.collection.p1": "Prikupljamo osobne podatke koje pružate pri kreiranju računa (ime, email, adresa za naplatu), podatke o plaćanju obrađene sigurno putem našeg pružatelja plaćanja, tehničke informacije automatski prikupljene (IP adrese, tip preglednika, operativni sustav) i podatke o korištenju.",
    "privacy.full.sharing.title": "Dijeljenje podataka",
    "privacy.full.sharing.p1": "Podatke dijelimo samo s: procesorima plaćanja (Stripe), pružateljima infrastrukture (EU podatkovni centri), registrima domena (ICANN akreditirani) i tijelima za provedbu zakona kada je to zakonski potrebno. Svi treći pružatelji ugovorno su obvezani GDPR-sukladnim ugovorima.",
    "privacy.full.cookies.title": "Kolačići i praćenje",
    "privacy.full.cookies.p1": "Koristimo strogo nužne kolačiće za autentifikaciju i upravljanje sesijama, te opcionalne analitičke kolačiće (uz vaš pristanak). Ne koristimo praćenje između web stranica niti prodajemo podatke oglašivačima.",
    "privacy.full.security.title": "Sigurnosne mjere",
    "privacy.full.security.p1": "Štitimo vaše podatke AES-256 enkripcijom, TLS 1.3 enkripcijom u prijenosu, redovitim testiranjima penetracije, kontrolom pristupa temeljenom na ulogama, 24/7 nadzorom infrastrukture i automatiziranom detekcijom prijetnji.",
    "privacy.full.rights.title": "Vaša prava (GDPR)",
    "privacy.full.rights.p1": "Pod GDPR-om imate pravo na: pristup osobnim podacima, ispravak netočnih podataka, brisanje podataka, ograničenje obrade, prijenos podataka, prigovor na obradu i povlačenje pristanka. Kontaktirajte dpo@webweaver.hr. Odgovorit ćemo unutar 30 dana.",
    "privacy.full.retention.title": "Čuvanje podataka",
    "privacy.full.retention.p1": "Vaše osobne podatke čuvamo samo koliko je potrebno za pružanje usluga i ispunjavanje zakonskih obveza. Podaci o računu čuvaju se za trajanja računa plus 90 dana. Zapisnici naplate čuvaju se 7 godina prema EU poreznim propisima.",
    "privacy.full.children.title": "Privatnost djece",
    "privacy.full.children.p1": "Naše usluge nisu namijenjene osobama mlađim od 16 godina. Ne prikupljamo svjesno osobne podatke djece. Ako saznamo da smo prikupili podatke od djeteta mlađeg od 16 godina, poduzet ćemo korake za brisanje tih informacija.",
    "privacy.full.contact.title": "Kontaktirajte nas",
    "privacy.full.contact.p1": "Za upite vezane za privatnost kontaktirajte našeg službenika za zaštitu podataka na dpo@webweaver.hr. Za opća pitanja obratite nam se na podrska@webweaver.hr ili +385 1 234 5678.",
    "privacy.full.termsLink": "Za informacije o uvjetima korištenja pogledajte naše",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
